jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
    - continue-on-error: true
      name: Cache Gradle User Files
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-gradle-user-home
        path: ~/.gradle
    - continue-on-error: true
      name: Cache Gradle Files
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-gradle-file
        path: ./.gradle
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      env:
        ARCLIGHT_FILES_TOKEN: ${{ secrets.ARCLIGHT_FILES_TOKEN }}
      name: Build
      run: './gradlew cleanBuild build collect uploadFiles --no-daemon --stacktrace

        '
    - continue-on-error: true
      name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Arclight
        path: ./build/libs/*.jar
name: Build
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
